n1 = int(input("Digite a primeira nota: "))
n2 = int(input("Digite a segunda nota: "))
n3 = int(input("Digite a terceira nota: "))
n4 = int(input("Digite a quarta nota: "))
soma = (n1 + n2 + n3 + n4)
media = (soma/4)
print("A média das notas digitadas fecha:", media)